# Basic ODK workflow
name: Docs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Install HDF5 & build h5py
        run: |
          apt-get update
          apt-get install -y libhdf5-dev
          pip install --upgrade "setuptools>=44.0.0"
          pip install --upgrade "wheel>=0.37.1"
          pip install --upgrade Cython
          pip install --no-binary=h5py h5py
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yaml
          REQUIREMENTS: requirements.txt
