name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip, setuptools & wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install HDF5 & h5py
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev python3-dev zlib1g-dev
          python -m pip install h5py

      - name: Install MkDocs & theme
        run: python -m pip install mkdocs mkdocs-material

      - name: Deploy docs via mkdocs
        run: |
          mkdocs gh-deploy \
            --config-file mkdocs.yaml \
            --clean \
            --strict \
            --message "Automated docs deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
